#!/usr/bin/env node
// Build script: Generate static data module for Vercel compatibility

const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, '../../data');
const outputFile = path.join(__dirname, 'providers-data.ts');

const providersPath = path.join(dataDir, 'providers.json');
const statsPath = path.join(dataDir, 'stats.json');

// Read data files
let providers = [];
let stats = {
  totalProviders: 0,
  onlineProviders: 0,
  todayNew: 0,
  lowestPrice: { model: "", price: 0, provider: "" },
  modelCoverage: [],
  priceDistribution: [],
  sourceDistribution: [],
  dailyTrend: [],
};

if (fs.existsSync(providersPath)) {
  const data = fs.readFileSync(providersPath, 'utf-8');
  providers = JSON.parse(data);
  console.log(`[build:data] Loaded ${providers.length} providers`);
}

if (fs.existsSync(statsPath)) {
  const data = fs.readFileSync(statsPath, 'utf-8');
  stats = JSON.parse(data);
}

// Generate TypeScript file
const output = `// Auto-generated by build script - DO NOT EDIT
// Generated at: ${new Date().toISOString()}

export const providersData = ${JSON.stringify(providers, null, 2)} as const;

export const statsData = ${JSON.stringify(stats, null, 2)} as const;
`;

fs.writeFileSync(outputFile, output);
console.log(`[build:data] Generated ${outputFile}`);
console.log(`[build:data] Providers: ${providers.length}`);
