// This file is auto-generated by the build process
// Data is embedded at build time for Vercel compatibility

export const providersData = [
  // Data will be copied from providers.json during build
] as const;

export const statsData = {
  totalProviders: 0,
  onlineProviders: 0,
  todayNew: 0,
  lowestPrice: { model: "", price: 0, provider: "" },
  modelCoverage: [],
  priceDistribution: [],
  sourceDistribution: [],
  dailyTrend: [],
} as const;
